apiVersion: v1
kind: Pod
metadata:
  name: declarative-pod
  labels: 
    pod: updated
spec:
  containers:
    - name: memory-demo-ctr
      image: redis
      env:
      - name: DEMO_GREETING
        value: "Hello from the environment"
      - name: DEMO_FAREWELL
        value: "Such a sweet sorrow"
